# Generated by Django 3.2.16 on 2025-03-25 12:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CaskVolumeCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='Объем бочeк')),
                ('slug', models.SlugField(unique=True, verbose_name='volume_URL')),
            ],
            options={
                'verbose_name': 'Объем бочки',
                'verbose_name_plural': 'Объемы бочек',
            },
        ),
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Производитель')),
                ('location', models.CharField(max_length=100, verbose_name='Страна')),
                ('website', models.URLField(verbose_name='Сайт')),
                ('slug', models.SlugField(unique=True, verbose_name='manufacturer_URL')),
            ],
            options={
                'verbose_name': 'Производитель',
                'verbose_name_plural': 'Производители',
            },
        ),
        migrations.CreateModel(
            name='TypeOfWood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Тип древесины')),
                ('slug', models.SlugField(unique=True, verbose_name='wood_URL')),
            ],
            options={
                'verbose_name': 'Тип древесины',
                'verbose_name_plural': 'Типы древесины',
            },
        ),
        migrations.CreateModel(
            name='Casks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='Не обязательно.', max_length=100, null=True, verbose_name='Название')),
                ('slug', models.SlugField(unique=True, verbose_name='cask_URL')),
                ('image', models.ImageField(upload_to='cask/images/%Y/%m/%d/', verbose_name='Изображение')),
                ('volume', models.FloatField(help_text='В литрах', verbose_name='Объем бочки')),
                ('start_of_operation', models.DateField(verbose_name='Дата начала эксплуатации бочки')),
                ('stop_of_operation', models.DateField(blank=True, help_text='Оставьте пустым, если бочка еще в работе.', null=True, verbose_name='Дата окончания эксплуатации бочки')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('time_update', models.DateTimeField(auto_now=True, verbose_name='Время обновления')),
                ('category_of_volume', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='casks', to='casks.caskvolumecategory', verbose_name='Объем бочки')),
                ('manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='casks', to='casks.manufacturer', verbose_name='Производитель')),
            ],
            options={
                'verbose_name': 'Бочка',
                'verbose_name_plural': 'Бочки',
                'ordering': ['-time_create'],
            },
        ),
    ]
