# Generated by Django 3.2.16 on 2025-03-25 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casks', '0003_auto_20250325_1944'),
    ]

    operations = [
        migrations.AddField(
            model_name='caskvolumecategory',
            name='description',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='caskvolumecategory',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Тип древесины'),
        ),
    ]
