# Generated by Django 3.2.16 on 2025-03-25 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casks', '0004_auto_20250325_1947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casks',
            name='image',
            field=models.ImageField(upload_to='casks/images/%Y/%m/%d/', verbose_name='Изображение'),
        ),
    ]
